#!/usr/bin/env python3
"""
One-shot environment setup for Perennia.

The backend refuses to start (app/config.py) unless SECRET_KEY,
ENCRYPTION_KEY, and ADMIN_PASSWORD_HASH are set in a .env file — this
script generates all three automatically so the app can actually boot.

Safe to run more than once: if .env already exists, it's left alone.

Usage:
    python scripts/setup_env.py
"""
import secrets
import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
ENV_PATH = BASE_DIR / ".env"
CREDS_PATH = BASE_DIR / "ADMIN_CREDENTIALS.txt"


def main():
    if ENV_PATH.exists():
        print("[setup] .env already exists — leaving it as is.")
        return

    try:
        import bcrypt
        from cryptography.fernet import Fernet
    except ImportError:
        print(
            "FATAL: dependencies are not installed yet.\n"
            "       Run install.bat (Windows) or ./install.sh (macOS/Linux) first.",
            file=sys.stderr,
        )
        sys.exit(1)

    admin_password = secrets.token_urlsafe(12)
    secret_key = secrets.token_urlsafe(48)
    encryption_key = Fernet.generate_key().decode()
    password_hash = bcrypt.hashpw(admin_password.encode("utf-8"), bcrypt.gensalt(rounds=12)).decode()

    env_contents = (
        "# Auto-generated by scripts/setup_env.py — keep this file private,\n"
        "# do not commit it, and do not share it.\n"
        f"SECRET_KEY={secret_key}\n"
        f"ENCRYPTION_KEY={encryption_key}\n"
        "ADMIN_USERNAME=admin\n"
        f"ADMIN_PASSWORD_HASH={password_hash}\n"
        "HOST=127.0.0.1\n"
        "PORT=8001\n"
        "# Local http (not https) — Secure cookies would otherwise be silently\n"
        "# dropped by the browser and admin login would appear to fail.\n"
        "COOKIE_SECURE=false\n"
        "\n"
        "# Optional: bind HTTPS directly on port 443 instead of plain HTTP on\n"
        "# PORT above. Fill in both paths and uncomment to enable — requires\n"
        "# Administrator/root privileges to bind port 443.\n"
        "# HTTPS_PORT=443\n"
        "# SSL_CERTFILE=C:\\path\\to\\fullchain.pem\n"
        "# SSL_KEYFILE=C:\\path\\to\\privkey.pem\n"
        "\n"
        "# Optional: appointment confirmation/reschedule/cancellation emails.\n"
        "# Fill in and uncomment to enable — without these, appointments still\n"
        "# work locally, they just won't send email notifications.\n"
        "# SMTP_HOST=smtp.example.com\n"
        "# SMTP_PORT=587\n"
        "# SMTP_USER=your-smtp-username\n"
        "# SMTP_PASSWORD=your-smtp-password\n"
        "# SMTP_FROM=Perennia <no-reply@perennia.com>\n"
        "# ADMIN_NOTIFY_EMAIL=info@perennia.com\n"
        "\n"
        "# Minimum notice (in hours) required to reschedule or cancel a booked\n"
        "# appointment. Defaults to 6 if not set.\n"
        "# APPT_MIN_NOTICE_HOURS=6\n"
    )
    ENV_PATH.write_text(env_contents, encoding="utf-8")

    CREDS_PATH.write_text(
        "Perennia admin login\n"
        "=====================\n"
        "URL:      http://127.0.0.1:8001/admin\n"
        "Username: admin\n"
        f"Password: {admin_password}\n\n"
        "This is the ONLY place this password is saved in plain text.\n"
        "Store it somewhere safe (e.g. a password manager) and delete this file.\n\n"
        "To change it later, run:\n"
        "  venv/bin/python scripts/gen_secrets.py --password \"your-new-password\"   (macOS/Linux)\n"
        "  venv\\Scripts\\python scripts\\gen_secrets.py --password \"your-new-password\"   (Windows)\n"
        "then replace the ADMIN_PASSWORD_HASH line in .env with the value it prints.\n",
        encoding="utf-8",
    )

    print("[setup] Created .env with fresh secrets.")
    print("[setup] Admin login saved to ADMIN_CREDENTIALS.txt:")
    print("           username: admin")
    print(f"           password: {admin_password}")
    print("[setup] Add your Anthropic API key from the admin panel after the server starts —")
    print("        it's encrypted at rest, so it's never typed directly into a file.")


if __name__ == "__main__":
    main()
